### ISSUE TITLE
Absolute values

### ISSUE THREAD

**Issue by hrrs01** [Nigecat/obsidian-desmos#100]
It might be that i am missing something, but in the regular desmos website, i am able to use absolute values in my funcitons. But because the argument splitter is the | symbol, i cannot get functions e.g. y = |x| to work. Is there any workarounds for this? Or could a possible solution be to make the argument splitter customizable? ( For my use cases, # or something would be better)

**Comment by Nigecat** [comment]
You can directly use the `\abs` function instead - 
![image](https://github.com/Nigecat/obsidian-desmos/assets/48661288/43928016-51bd-4349-a465-6fd6fcee4119)
