### ISSUE TITLE
Plugin does not render Desmos distributions

### ISSUE THREAD

**Issue by yustarandomname** [Nigecat/obsidian-desmos#103]
**Describe the bug**
Desmos has some built-in helper functions to draw distributions. You can find more information on their website here: [Desmos Distributions](https://help.desmos.com/hc/en-us/articles/360022401451-Distributions). However, these functions do not render properly for the Desmos-Graph Obsidian plugin and result in an error stating that the function is not defined.

**Expected behaviour**

for function `f = uniformdist(0,1)`. Have the output as shown in the screenshot

**Screenshots**
<img width="856" alt="image" src="https://github.com/Nigecat/obsidian-desmos/assets/25432790/a6275f9e-5ccc-4ee1-8d55-f913be57a363">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Obsidian Version: 1.4.16
 - Plugin Version: 0.6.6

**Comment by Nigecat** [comment]
For it to be detected as an internal function, it needs to be prefixed with a `\` (I should probably document this somewhere) - 
![image](https://github.com/Nigecat/obsidian-desmos/assets/48661288/768b9b1d-edbe-4d91-907d-40fb5126dfa3)
