### ISSUE TITLE
How the hell do I do |absolute value| ?

### ISSUE THREAD

**Issue by l1mey112** [Nigecat/obsidian-desmos#105]
**Describe the bug**
Using `|absolute value|` conflicts with the custom styling control.

**Expected behavior**
A proper absolute value function.

**Screenshots**

![image](https://github.com/Nigecat/obsidian-desmos/assets/66291634/56ba2b1f-a1e3-4b94-b90a-50b0ec0414da)

![image](https://github.com/Nigecat/obsidian-desmos/assets/66291634/4666e06d-c764-45ab-b51b-c7224c6a086d)

**Comment by Nigecat** [comment]
You can use the `\abs( )` function - 
![image](https://github.com/Nigecat/obsidian-desmos/assets/48661288/f1246f2a-9c84-47be-9faf-d5fab5d9cb29)
