### ISSUE TITLE
Invalid bounds while bounds are correct

### ISSUE THREAD

**Issue by Ravenightwing** [Nigecat/obsidian-desmos#110]
**Describe the bug**
 Invalid bounds argument. Expected a bounds object with bounds.bottom < bounds.top, and bounds.left < bounds.right. Got {"left":-10,"right":10,"bottom":null,"top":null}
Meanwhile, I set
```
top=20;
bottom=-10;
left=-10;
right=10;
```
**Expected behavior**
The graph should render, instead it closed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Obsidian Version: 1.5.11
 - Plugin Version: 0.6.6

**Additional context**

**Comment by Nigecat** [comment]
Can you send the full source? That seems to work fine for me - 
![image](https://github.com/Nigecat/obsidian-desmos/assets/48661288/8677533d-3721-49eb-9d70-d2d8d33b8577)

**Comment by Ravenightwing** [comment]
> Can you send the full source? That seems to work fine for me - ![image](https://private-user-images.githubusercontent.com/48661288/338788181-8677533d-3721-49eb-9d70-d2d8d33b8577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjI2NTgsIm5iZiI6MTcxODE2MjM1OCwicGF0aCI6Ii80ODY2MTI4OC8zMzg3ODgxODEtODY3NzUzM2QtMzcyMS00OWViLTlkNzAtZDJkOGQzM2I4NTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAzMTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0M2EwMTdjOTE4NDkxOWIwZmE5NWY0NGIxY2UzOWIzYWQ2ZTZjNjM3YTI3NDM4YTUxMTIwMThlZDkzNmRmY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7U3D2YjR57w3fkcCTfiC9vVoraVnai0f8g77RnhLItQ)

It works now, so i would close the issue. Thanks!
