### ISSUE TITLE
Inequalities: hide lines but show shading

### ISSUE THREAD

**Issue by ferife** [Nigecat/obsidian-desmos#111]
I want the ability to write inequalities in such a way that the line for the equation is hidden, but the semi-transparent shading for the area covered by the inequality is still shown

[This](https://www.desmos.com/calculator/dkbh1pbovs) is a link to a Desmos graph that looks exactly like what I'm hoping for. 

[This](https://www.desmos.com/calculator/dumehignv8) is a link to a graph with the exact same equations, but as it currently appears in the Obsidian plugin

This is mainly useful for visualizing definite integrals.

**Comment by Nigecat** [comment]
See #118
