### ISSUE TITLE
Set axes to scale logarithmically

### ISSUE THREAD

**Issue by ferife** [Nigecat/obsidian-desmos#112]
On the desmos website, if you click the wrench icon to the right of the graph, there will be various options to control the way the graph is displayed. If you click the "More options" dropdown, you can set the x and y axes to scale logarithmically instead of linearly. I would like this option in the obsidian version as well

**Comment by Nigecat** [comment]
This can be done with `xAxisLogarithmic` and `yAxisLogarithmic` now - 
![image](https://github.com/Nigecat/obsidian-desmos/assets/48661288/97fa6f97-44b1-411e-9167-bcd9ffe4e324)
