### ISSUE TITLE
Absolute value functions conflicting with piecewise

### ISSUE THREAD

**Issue by Cyprinus478** [Nigecat/obsidian-desmos#113]
I am trying to graph |x|, -|x|, and sin(x) to display squeeze theory at the limit of 0, however, the plug-in won't allow the graphing of absolute values of x.

trying to graph with the code 

```desmos-graph
y=\sin(x)
y=|x|
y=-|x|
```

shows the error: Desmos Graph Error: A piecewise expression must have at least one condition.

interesting note: entering

```desmos-graph
y=\sin(x)
y=|x|
```

does not display an error however the absolute value function is not displayed

**Comment by Nigecat** [comment]
You need to use the `abs` function directly, for example:
```
y=\abs(x)
```
