### ISSUE TITLE
No update possible since yesterday

### ISSUE THREAD

**Issue by merlinuwe** [Nigecat/obsidian-desmos#121]
![image](https://github.com/Nigecat/obsidian-desmos/assets/4138869/e88b54c9-69d8-4cc1-bf5d-58ce3b44a456)

SYSTEM INFO:
	Obsidian version: v1.6.3
	Installer version: v1.6.3
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.6.0
	Snippets enabled: 36
	Restricted mode: off
	Plugins installed: 149
	Plugins enabled: 58
		1: Set View Mode per Note v1.0.3
		2: Admonition v10.3.2
		3: Advanced Tables v0.21.0
		4: Advanced URI v1.40.1
		5: Android nomedia v0.1.0
		6: Auto Link Title v1.5.4
		7: Beautitab v1.6.1
		8: Better Export PDF v1.8.1
		9: Commander v0.5.1
		10: Colored Tags Wrangler v0.19.3
		11: Copy document as HTML v0.7.0
		12: Creases v0.7.0
		13: Custom Classes v2.6.1
		14: Dictionary v2.22.0
		15: Docxer v1.0.2
		16: Editing Toolbar v2.4.16
		17: Editor Commands Remap v1.0.2
		18: Editor Syntax Highlight v0.1.3
		19: Enhancing Export v1.10.6
		20: Excel to Markdown Table v0.4.0
		21: Export Image plugin v2.3.10
		22: File Explorer Note Count v1.2.2
		23: Google Calendar v1.10.14
		24: Linter v1.24.0
		25: Local Backup v0.1.7
		26: markdown export v1.0.21
		27: Natural Language Dates v0.6.2
		28: Navigate Cursor History v1.1.0
		29: Note Toolbar v1.7.28
		30: Number Headings v1.16.0
		31: Omnisearch v1.23.1
		32: Paste image rename v1.6.1
		33: Quick Explorer v0.2.8
		34: Quiet Outline v0.3.33
		35: Recent Files v1.4.1
		36: Scroll to Top v2.1.4
		37: Settings Management v1.0.5
		38: Sheet Plus v1.2.0
		39: Show Current File Path v0.5.2
		40: Sortable v0.3.1
		41: Status Bar Organizer v2.0.2
		42: Style Settings v1.0.8
		43: Supercharged Links v0.12.1
		44: Symbols Prettifier v1.1.4
		45: Tag Wrangler v0.6.1
		46: Tasks v7.5.0
		47: Templater v2.3.3
		48: Text Extractor v0.5.2
		49: Todo sort v1.0.0
		50: Translate v1.4.8
		51: Typing Transformer v0.4.0
		52: Vault Changelog v0.1.0
		53: Vault Statistics v0.1.3
		54: Webpage HTML Export v1.8.01
		55: Link Converter v0.1.6
		56: Date Inserter v0.3.3
		57: Dataview v0.5.67
		58: Desmos v0.6.7

**Comment by Nigecat** [comment]
Looks like I uploaded the wrong release file, should work now/whenever it clears their cache.

**Comment by merlinuwe** [comment]
Works now, thank you very much.
