### ISSUE TITLE
domains dont work

### ISSUE THREAD

**Issue by JamesDundon05** [Nigecat/obsidian-desmos#3]
```desmos-graph
boundry_left=-1;
boundry_bottom=-1;
boundry_top=10
---
f(x)=1.66655x {x>0}
(5, 8.33)
```
Results in: Desmos Graph Error: Sorry, I don't understand the way that '=' is used here.
Backslash does not fix (between x and curly bracket)

**Comment by Nigecat** [comment]
Fixed in 74f3f69
