### ISSUE TITLE
Allow differentiation in the form f'(x)

### ISSUE THREAD

**Issue by Bahnschrift** [Nigecat/obsidian-desmos#33]
Given a function defined in the form `f(x)=...`, I can't find a way to display the derivative of it. I've tried the syntax
````
```desmos-graph
f(x)=x^2
f'(x)
```
````
would be valid, but it gives the error: `Desmos Graph Error: Too many variables. Try defining 'd'.`

**Comment by Nigecat** [comment]
Turns out this was also a bug in the parser.
