### ISSUE TITLE
Add labels to points

### ISSUE THREAD

**Issue by SandWoodJones** [Nigecat/obsidian-desmos#46]
Desmos already has a feature where you can give custom labels to (x,y) pairs.
For example:
![image](https://user-images.githubusercontent.com/35671374/162644738-122a7b4b-4c13-496c-bb09-2f5922bd7a0e.png)
Generates:
![image](https://user-images.githubusercontent.com/35671374/162644794-7160cece-677f-4464-acc4-2c5e1722a414.png)
This feature would help greatly with how I write my notes.

**Comment by Nigecat** [comment]
Added in release v0.6.2
