### ISSUE TITLE
Bounds on equations.

### ISSUE THREAD

**Issue by wylited** [Nigecat/obsidian-desmos#51]
Allow for bounds for equations.

I would like this feature to be able to make economic graphs (for school) using this tool.

ie: y=5:0<x<5 the line will only show a value of y=5 on a range of x between 0-5.

**Comment by Nigecat** [comment]
This is already supported (though docs could be a bit clearer since it's a bit buried and mixed with the color + style configuration), for the mentioned example you could do:
````
    ```desmos-graph
        y=5|0<x<5
    ```
````
