### ISSUE TITLE
Admonition Integration

### ISSUE THREAD

**Issue by ndharari** [Nigecat/obsidian-desmos#52]
Hi there!
Your plugin is amazing man. One small thing, it would be great if we could integrate it with the Admonition Plugin. Right now, when I try to use the codeblock syntax it breaks, as the desmos graph cannot be nested in an admonition. 

Maybe a diferent syntax only for this case, using ~~~ instead of ````?

**Comment by Nigecat** [comment]
Could you include an example of the content that doesn't work? When I try it locally both the integrated Obsidian Callouts and Admonition blocks work fine - 
![image](https://user-images.githubusercontent.com/48661288/163651108-bad7508e-1b68-438a-bfad-8f9e1c47b50f.png)
(Using the syntax outlined [here](https://github.com/valentine195/obsidian-admonition#rendering-code-blocks-inside-admonitions) for the Admonition plugin)

**Comment by ndharari** [comment]
Hi, sorry for the delay. After a little testing, found that the problem arrises only in live preview


```ad-exer
title: Ejercicio

~~~desmos-graph
x+y=4
~~~

this is ment to be inside the admonition
```

where the latter text does not appear to be in the admonition. In reading mode though its ok.

**Comment by Nigecat** [comment]
Weird, that first example works fine for me in live preview mode - 
![image](https://user-images.githubusercontent.com/48661288/163691430-5c76929a-88c0-4e71-a4b8-d6e258c93125.png)
![image](https://user-images.githubusercontent.com/48661288/163691435-d12b7d74-2f24-424f-b2de-d8029238a7e4.png)

I'll have a further look into the live preview mode since I usually don't use it so there may be bugs in the way it handles input.

**Comment by ndharari** [comment]
![image](https://user-images.githubusercontent.com/41973171/163692669-b4512f61-9989-4769-a4fe-b036316a2523.png)

I attach the output so you can see the problem i was refering then

**Comment by Nigecat** [comment]
> Hi, sorry for the delay. After a little testing, found that the problem arrises only in live preview
> 
> ``````
> ```ad-exer
> title: Ejercicio
> 
> ~~~desmos-graph
> x+y=4
> ~~~
> 
> this is ment to be inside the admonition
> ```
> ``````

Is `ad-exer` a custom Admonition block? If I copy this content nothing happens since Obsidian does not seem to know about this codeblock type even with the Admonition plugin installed (unless you're using a different plugin than [this one](https://github.com/valentine195/obsidian-admonition)).

**Comment by ndharari** [comment]
Yes, really sorry, it is.  Same behaviour while using the note adm though.

**Comment by Nigecat** [comment]
I'm going to tag this as needs-more-info for now, as I still can't reproduce it... If you are still having the problem could you potentially create a vault with just the configuration to trigger this issue and upload it?

**Comment by ndharari** [comment]
So I created a new vault and the problem is not there, so its surely a problem with another plugin I have installed. 
If you want to close the issue now, given thats a minor bug on my setup its ok
thanks for the support!
