### ISSUE TITLE
Label on a point is broken

### ISSUE THREAD

**Issue by ndharari** [Nigecat/obsidian-desmos#53]
I tried to create the following graph
~~~desmos-graph
left=-10; right=10;
top=10; bottom=-10;
height=300; width=300;
---
y=\sin(x)
(0,0) | label:(0,0)
~~~

Got this error
Desmos Graph Error: The left side of a ':' must be a condition, like 'x>1'.

**Comment by Nigecat** [comment]
I think you might be using an outdated version of the plugin, the label feature was only added in v0.6.2 released a couple days ago (that graph renders fine on the latest version)

**Comment by ndharari** [comment]
Oh sorry, my bad
