### ISSUE TITLE
Center Graphs

### ISSUE THREAD

**Issue by ndharari** [Nigecat/obsidian-desmos#54]
A nice and simple way to center graphs would be really cool!

**Comment by ndharari** [comment]
maybe a global setting? I always use my images centered so i would keep it always this way

**Comment by Nigecat** [comment]
Do you mean to center the rendered graph in the page content? I've been intending to add a CSS class to the rendered graphs for styling purposes so if that's the case it could (probably) be done via a style override once that's implemented.

**Comment by Nigecat** [comment]
This can now be done with the latest version (v0.6.3) and a CSS snippet, see [Custom Styling](https://github.com/Nigecat/obsidian-desmos#custom-styling).

**Comment by ndharari** [comment]
Sorry to bother. It may be something at my end but the snippet only works on live preview, in reading and export the graph is on the left
