### ISSUE TITLE
A question about drawing a line between points

### ISSUE THREAD

**Issue by omergunr100** [Nigecat/obsidian-desmos#58]
First of all I just wanted to say that your plugin is absolutely awesome!

It's a minor thing, but I wanted to know if there's a way to draw a line between 2 point, like this:
![image](https://user-images.githubusercontent.com/24607757/166109700-fe32f5ed-fa64-4798-b4c2-676d999d2f31.png)

Thanks again for putting in the effort to create this amazing plugin :)

**Comment by Nigecat** [comment]
There's currently no way to directly draw a line between two points, however you can emulate it by drawing the two points then separately adding a line with a domain restriction, for example:
````
```desmos-graph
left=-1; right=2;
bottom=-1; top=2;
defaultColor=red;
---
(0,0)|label:(0,0)
(1,1)|label:(1,1)
y=x|0<=x<=1
```
````
Would result in:
![image](https://user-images.githubusercontent.com/48661288/166125427-24f3f16f-01b7-485e-ad83-9000adf95362.png)

**Comment by omergunr100** [comment]
Ok, thank you :)
