### ISSUE TITLE
LaTeX format does not work in graph restrictions 🧇 

### ISSUE THREAD

**Issue by th4lmain** [Nigecat/obsidian-desmos#9]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/77910773/158977617-0ac58ed8-0644-4010-a612-06587640c902.png">

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/77910773/158977954-fb3d67bc-f9dc-4cab-9e17-8d297e6746c2.png">

**Comment by Nigecat** [comment]
This is an unsupported feature by the Desmos API so we cannot add support for it. 
However, a better error message would be a good idea.
